Update manifests to more closely align with OCP
openshift/microshift pull request #1029
Opened 2022-10-19 09:51 UTC by fzdarsky

Small updates to the rebase script and the produced assets to more closely match OCP's deployments.

Signed-off-by: Frank A. Zdarsky <fzdarsky@redhat.com>

Closes USHIFT-421

2022-10-19 17:11 UTC, dhellmann commented
This looks OK to me. I'll hold off the lgtm until we sort out CI to avoid unnecessary retests.

2022-10-25 18:41 UTC, pmtk commented
/retest-required

2022-10-28 09:52 UTC, pmtk requested changes

2022-10-28 09:52 UTC, pmtk commented on pkg/assets/bindata.go
> +        log . {
Please remove bindata.go from your PR

2022-11-03 11:00 UTC, fzdarsky commented on pkg/assets/bindata.go
> +        log . {
done

2022-11-03 15:23 UTC, pmtk commented
/lgtm

2022-11-03 17:40 UTC, ggiguash commented
/retest

2022-11-03 18:21 UTC, merged