OSDOCS-4447: Add CNI doc
openshift/microshift pull request #1078
Opened 2022-11-02 03:30 UTC by zshi-redhat

2022-11-02 15:10 UTC, mangelajo requested changes
Some comments, nice work.

2022-11-03 01:47 UTC, zshi-redhat commented on docs/default_cni_plugin.md
> +2. Global config dir: `/etc/microshift/ovn.yaml`
Fixed.

2022-11-03 01:48 UTC, zshi-redhat commented on docs/default_cni_plugin.md
> +
Added TODO comment to replace ovs cmds with nmcli (comment is only visible in text).

2022-11-03 01:48 UTC, zshi-redhat commented on docs/default_cni_plugin.md
> +* East-west multicast
Removed multicast.

2022-11-03 01:48 UTC, zshi-redhat commented on docs/default_cni_plugin.md
> +This is done by specifying the desired host interface name in a hint file `/var/lib/ovnk/iface_default_hint`.
I will update this once we add support in configure-ovs.sh script.

2022-11-03 08:54 UTC, mangelajo approved these changes
/lgtm

2022-11-03 09:15 UTC, merged