upload CI built RPMs to s3 Cache
openshift/microshift pull request #2617
Opened 2023-11-16 09:06 UTC by eslutsky

2023-11-16 09:38 UTC, ggiguash commented on test/bin/manage_build_cache.sh
> +    echo "Uploading ${rpm_size} of rpms to '${rpm_dst}'"
```suggestion
    echo "Uploading ${rpm_size} of RPMs to '${rpm_dst}'"
```

2023-11-16 10:58 UTC, ggiguash requested changes

2023-11-16 10:58 UTC, ggiguash commented on test/bin/manage_build_cache.sh
I've a bit of a problem with the non-symmetric implementation of RPM upload, while no download / verify operations were implemented.

We cannot implement download the way it is now because that would override the CI RPM artfifacts. So, we should think about how to implement this properly.

Can I suggest uploading and downloading into a special rpm-source-cache directory? This way, the CI will simply ignore these files and we should be able to use them explicitly when necessary.

2023-11-16 14:26 UTC, eslutsky commented on test/bin/manage_build_cache.sh
for download case it does make sense  to save them  outside "${RPM_SOURCE}" directory, and yes,  its only downloaded  on special  cases when explicitly required.
for upload either way will work  for example: ${dst_base}/rpm-source-cache/ ?

2023-11-16 14:30 UTC, ggiguash commented on test/bin/manage_build_cache.sh
So, to be explicit:
- When uploading RPMs, we should tar them up and save them at `${AWS_BUCKET_NAME}/<branch>/<arch>/<tag>/rpm-source-cache.tar`
- When downloading RPMs, we should unpack them at `${IMAGEDIR}/rpm-source-cache.tar`
- The `valid` operation should check for presence of `${AWS_BUCKET_NAME}/<branch>/<arch>/<tag>/rpm-source-cache.tar` in the bucket.

Does it make sense?

2023-11-21 09:12 UTC, eslutsky commented
closing for now

2023-11-21 09:12 UTC, closed without merging