tighten permissions on configuration data files
openshift/microshift pull request #769
Opened 2022-07-13 14:58 UTC by sallyom

also, small fix to the apiserver-audit-log path

**Which issue(s) this PR addresses**:

Closes [USHIFT-84](https://issues.redhat.com/browse/USHIFT-84)

2022-07-13 15:01 UTC, ggiguash requested changes
Since we're specifying a mask/mode for directory creation, it must be at least 0700 to have x bit set for the owner. Otherwise, cd would not work into that directory

2022-07-13 16:25 UTC, ggiguash approved these changes

2022-07-13 16:26 UTC, ggiguash commented
/approve

2022-07-13 19:01 UTC, dhellmann reviewed
I had one question that can be addressed in another PR if needed.

/lgtm

2022-07-13 19:01 UTC, dhellmann commented on pkg/controllers/openshift-apiserver.go
> +  auditFilePath: "`+cfg.AuditLogDir+`/openshift-apiserver-audit.log"
Will the need for that slash depend on whether the AuditLogDir variable ends in one? Should we use filepath.Join()?

2022-07-13 19:29 UTC, merged

2022-07-21 15:17 UTC, ggiguash commented
USHIFT-84