cleanup ovn kubernetes CNI binary and config file
openshift/microshift pull request #877
Opened 2022-08-22 10:27 UTC by zshi-redhat

ovn-kubernetes CNI config file is written by ovnkube-node
process and will be left over if ovnkube-node doesn't
exit gracefully (which is the case when stopping MicroShift
service).

Crio waits for the existence of ovn-kubernetes CNI config
to mark the node as Ready. If ovn-kubernetes CNI config is
not cleaned up, node will become ready immediately on next
boot w/o waiting for ovn network become ready.

Signed-off-by: Zenghui Shi <zshi@redhat.com>

2022-08-22 11:43 UTC, ggiguash requested changes

2022-08-22 11:43 UTC, ggiguash commented on hack/cleanup.sh
> +    rm -rf /opt/cni/bin/ovn-k8s-cni-overlay
These are files, not directories, so can we use "rm -f" command?

2022-08-22 12:29 UTC, ggiguash approved these changes

2022-08-22 12:29 UTC, ggiguash commented
/lgtm

2022-08-22 13:08 UTC, merged

2022-09-09 13:10 UTC, dhellmann commented
USHIFT-386