USHIFT-365: support ipv4.ignore-auto-dns on ovs-interface br-ex
openshift/microshift pull request #937
Opened 2022-09-08 01:48 UTC by zshi-redhat

Closes #[USHIFT-365](https://issues.redhat.com//browse/USHIFT-365)

2022-09-08 02:46 UTC, zshi-redhat commented
CI fails to resolve github.com when ipv4.ignore-auto-dns is configured:
```
+ curl -sSLo /home/rhel8user/bin/kuttl https://github.com/kudobuilder/kuttl/releases/download/v0.10.0/kubectl-kuttl_0.10.0_linux_x86_64
curl: (6) Could not resolve host: github.com
```

2022-09-09 09:59 UTC, zshi-redhat commented
/retest

2022-09-14 07:55 UTC, mangelajo commented on packaging/systemd/configure-ovs.sh
> +      fi
let's add also ipv6 support

https://bugzilla.redhat.com/show_bug.cgi?id=1261428

ipv6.ignore-auto-dns and let's avoid future bugs :), dns settings are exposed via router advertisement, or DHCPv6

2022-09-14 07:56 UTC, mangelajo requested changes
see comments (IPv6)

2022-09-14 20:05 UTC, mangelajo commented
Hey, I tested it here and doesn't seem to be working:
```
[redhat@localhost ~]$ sudo su -
[root@localhost ~]# nmcli c s
NAME                UUID                                  TYPE      DEVICE
Wired connection 1  c64f514e-a3db-39ee-bc31-069d6edca134  ethernet  enp1s0
[root@localhost ~]# nmcli c s "Wired connection 1" | grep dns
connection.mdns:                        -1 (default)
connection.dns-over-tls:                -1 (default)
ipv4.dns:                               8.8.8.8
ipv4.dns-search:                        --
ipv4.dns-options:                       --
ipv4.dns-priority:                      0
ipv4.ignore-auto-dns:                   yes
ipv6.dns:                               --
ipv6.dns-search:                        --
ipv6.dns-options:                       --
ipv6.dns-priority:                      0
ipv6.ignore-auto-dns:                   no
[root@localhost ~]# ovs-
ovs-appctl     ovs-bugtool    ovs-dpctl      ovs-dpctl-top  ovs-ofctl      ovs-pki        ovs-vsctl      ovs-vswitchd
[root@localhost ~]# configure-ovs.sh OVNKubernetes
+ touch /var/run/ovs-config-executed
+ NM_CONN_PATH=/etc/NetworkManager/system-connections
+ nm_config_changed=0
+ MANAGED_NM_CONN_SUFFIX=-slave-ovs-clone
+ BRIDGE_METRIC=48
+ BRIDGE1_METRIC=49
+ trap handle_exit EXIT
+ '[' '!' -f /etc/cno/mtu-migration/config ']'
+ echo 'Cleaning up left over mtu migration configuration'
Cleaning up left over mtu migration configuration
+ rm -rf /etc/cno/mtu-migration
+ rpm -qa
+ grep -q openvswitch
+ print_state
+ echo 'Current device, connection, interface and routing state:'
Current device, connection, interface and routing state:
+ nmcli -g all device
+ grep -v unmanaged
enp1s0:ethernet:connected:full:full:/org/freedesktop/NetworkManager/Devices/2:Wired connection 1:c64f514e-a3db-39ee-bc31-069d6edca134:/org/freedesktop/NetworkManager/ActiveConnection/1
+ nmcli -g all connection
Wired connection 1:c64f514e-a3db-39ee-bc31-069d6edca134:802-3-ethernet:1663185689:Wed 14 Sep 2022 04\:01\:29 PM EDT:yes:-999:no:/org/freedesktop/NetworkManager/Settings/1:yes:enp1s0:activated:/org/freedesktop/NetworkManager/ActiveConnection/1::/etc/NetworkManager/system-connections/Wired connection 1.nmconnection
+ ip -d address show
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00 promiscuity 0 minmtu 0 maxmtu 0 numtxqueues 1 numrxqueues 1 gso_max_size 65536 gso_max_segs 65535
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host
       valid_lft forever preferred_lft forever
2: enp1s0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UP group default qlen 1000
    link/ether 52:54:00:06:7a:19 brd ff:ff:ff:ff:ff:ff promiscuity 0 minmtu 68 maxmtu 65535 numtxqueues 1 numrxqueues 1 gso_max_size 65536 gso_max_segs 65535
    inet 192.168.122.238/24 brd 192.168.122.255 scope global dynamic noprefixroute enp1s0
       valid_lft 3208sec preferred_lft 3208sec
    inet6 fe80::3eca:efc4:4c89:279f/64 scope link noprefixroute
       valid_lft forever preferred_lft forever
+ ip route show
default via 192.168.122.1 dev enp1s0 proto dhcp src 192.168.122.238 metric 100
192.168.122.0/24 dev enp1s0 proto kernel scope link src 192.168.122.238 metric 100
+ ip -6 route show
::1 dev lo proto kernel metric 256 pref medium
fe80::/64 dev enp1s0 proto kernel metric 1024 pref medium
+ '[' OVNKubernetes == OVNKubernetes ']'
+ ovnk_config_dir=/etc/ovnk
+ ovnk_var_dir=/var/lib/ovnk
+ extra_bridge_file=/etc/ovnk/extra_bridge
+ iface_default_hint_file=/var/lib/ovnk/iface_default_hint
+ mkdir -p /etc/ovnk
+ mkdir -p /var/lib/ovnk
++ get_iface_default_hint /var/lib/ovnk/iface_default_hint
++ local iface_default_hint_file=/var/lib/ovnk/iface_default_hint
++ '[' -f /var/lib/ovnk/iface_default_hint ']'
++ echo ''
+ iface_default_hint=
+ '[' '' == '' ']'
++ get_bridge_physical_interface ovs-if-phys0
++ local bridge_interface=ovs-if-phys0
++ local physical_interface=
+++ nmcli -g connection.interface-name conn show ovs-if-phys0
+++ echo ''
++ physical_interface=
++ echo ''
+ current_interface=
+ '[' '' '!=' '' ']'
+ '[' -f /var/lib/ovnk/iface_default_hint ']'
+ '[' '!' -f /run/configure-ovs-boot-done ']'
+ echo 'Running on boot, restoring previous configuration before proceeding...'
Running on boot, restoring previous configuration before proceeding...
+ rollback_nm
++ get_bridge_physical_interface ovs-if-phys0
++ local bridge_interface=ovs-if-phys0
++ local physical_interface=
+++ nmcli -g connection.interface-name conn show ovs-if-phys0
+++ echo ''
++ physical_interface=
++ echo ''
+ phys0=
++ get_bridge_physical_interface ovs-if-phys1
++ local bridge_interface=ovs-if-phys1
++ local physical_interface=
+++ nmcli -g connection.interface-name conn show ovs-if-phys1
+++ echo ''
++ physical_interface=
++ echo ''
+ phys1=
+ remove_all_ovn_bridges
+ echo 'Reverting any previous OVS configuration'
Reverting any previous OVS configuration
+ remove_ovn_bridges br-ex phys0
+ bridge_name=br-ex
+ port_name=phys0
+ update_nm_conn_files br-ex phys0
+ bridge_name=br-ex
+ port_name=phys0
+ ovs_port=ovs-port-br-ex
+ ovs_interface=ovs-if-br-ex
+ default_port_name=ovs-port-phys0
+ bridge_interface_name=ovs-if-phys0
+ MANAGED_NM_CONN_FILES=($(echo "${NM_CONN_PATH}"/{"$bridge_name","$ovs_interface","$ovs_port","$bridge_interface_name","$default_port_name"}{,.nmconnection}))
++ echo /etc/NetworkManager/system-connections/br-ex /etc/NetworkManager/system-connections/br-ex.nmconnection /etc/NetworkManager/system-connections/ovs-if-br-ex /etc/NetworkManager/system-connections/ovs-if-br-ex.nmconnection /etc/NetworkManager/system-connections/ovs-port-br-ex /etc/NetworkManager/system-connections/ovs-port-br-ex.nmconnection /etc/NetworkManager/system-connections/ovs-if-phys0 /etc/NetworkManager/system-connections/ovs-if-phys0.nmconnection /etc/NetworkManager/system-connections/ovs-port-phys0 /etc/NetworkManager/system-connections/ovs-port-phys0.nmconnection
+ shopt -s nullglob
+ MANAGED_NM_CONN_FILES+=(${NM_CONN_PATH}/*${MANAGED_NM_CONN_SUFFIX}.nmconnection ${NM_CONN_PATH}/*${MANAGED_NM_CONN_SUFFIX})
+ shopt -u nullglob
+ rm_nm_conn_files
+ for file in "${MANAGED_NM_CONN_FILES[@]}"
+ '[' -f /etc/NetworkManager/system-connections/br-ex ']'
+ for file in "${MANAGED_NM_CONN_FILES[@]}"
+ '[' -f /etc/NetworkManager/system-connections/br-ex.nmconnection ']'
+ for file in "${MANAGED_NM_CONN_FILES[@]}"
+ '[' -f /etc/NetworkManager/system-connections/ovs-if-br-ex ']'
+ for file in "${MANAGED_NM_CONN_FILES[@]}"
+ '[' -f /etc/NetworkManager/system-connections/ovs-if-br-ex.nmconnection ']'
+ for file in "${MANAGED_NM_CONN_FILES[@]}"
+ '[' -f /etc/NetworkManager/system-connections/ovs-port-br-ex ']'
+ for file in "${MANAGED_NM_CONN_FILES[@]}"
+ '[' -f /etc/NetworkManager/system-connections/ovs-port-br-ex.nmconnection ']'
+ for file in "${MANAGED_NM_CONN_FILES[@]}"
+ '[' -f /etc/NetworkManager/system-connections/ovs-if-phys0 ']'
+ for file in "${MANAGED_NM_CONN_FILES[@]}"
+ '[' -f /etc/NetworkManager/system-connections/ovs-if-phys0.nmconnection ']'
+ for file in "${MANAGED_NM_CONN_FILES[@]}"
+ '[' -f /etc/NetworkManager/system-connections/ovs-port-phys0 ']'
+ for file in "${MANAGED_NM_CONN_FILES[@]}"
+ '[' -f /etc/NetworkManager/system-connections/ovs-port-phys0.nmconnection ']'
+ ovs-vsctl --timeout=30 --if-exists del-br br-ex
+ '[' -d /sys/class/net/br-ex1 ']'
+ echo 'OVS configuration successfully reverted'
OVS configuration successfully reverted
+ reload_profiles_nm '' ''
+ '[' 0 -eq 0 ']'
+ return
+ print_state
+ echo 'Current device, connection, interface and routing state:'
Current device, connection, interface and routing state:
+ nmcli -g all device
+ grep -v unmanaged
enp1s0:ethernet:connected:full:full:/org/freedesktop/NetworkManager/Devices/2:Wired connection 1:c64f514e-a3db-39ee-bc31-069d6edca134:/org/freedesktop/NetworkManager/ActiveConnection/1
+ nmcli -g all connection
Wired connectio [...]

2022-09-15 01:07 UTC, zshi-redhat commented
@mangelajo  could you check the `ovs-if-br-ex` interface name with device type being `ovs-interface`?
There are three nmcli devices named `br-ex` with different types: ovs-bridge, ovs-port and ovs-interface; every ovs-interface needs to be associated with ovs-port. the ignore-auto-dns settings are applied to ovs-interface.

2022-09-15 07:50 UTC, mangelajo commented
Oh, you are right, ignore dns is there, but the DNS setting I used (8.8.8.8) is not propagated so I don't have DNS now
```
[redhat@localhost ~]$ nmcli c s ovs-if-br-ex | grep dns
connection.mdns:                        -1 (default)
connection.dns-over-tls:                -1 (default)
ipv4.dns:                               --           <--------------------------
ipv4.dns-search:                        --
ipv4.dns-options:                       --
ipv4.dns-priority:                      0
ipv4.ignore-auto-dns:                   yes
ipv6.dns:                               --
ipv6.dns-search:                        --
ipv6.dns-options:                       --
ipv6.dns-priority:                      0
ipv6.ignore-auto-dns:                   no
```
on the original interface it was:
```
ipv4.dns:                               8.8.8.8
```
I assume we need to copy that too for ipv6.dns

2022-09-15 07:54 UTC, mangelajo commented
I also suspect we would have the same issue with other dns parameters, like dns search/options/mdns, dns-over-tls, etc. We need a generic solution for that, may be we need an extended JIRA to look at those?

2022-09-15 08:12 UTC, zshi-redhat commented
> I also suspect we would have the same issue with other dns parameters, like dns search/options/mdns, dns-over-tls, etc. We need a generic solution for that, may be we need an extended JIRA to look at those?

We could add those dns options in configure-ovs.sh just like ipv4.ignore-auto-dns if there is a use case for that. This approach is a bit cumbersome since it needs to selectively add each option when required. I agree we shall explore a generic solution or provide alternative to skip the configure-ovs.sh.

2022-09-15 08:22 UTC, mangelajo approved these changes
/lgtm

2022-09-15 14:50 UTC, ggiguash commented
/retest

2022-09-15 23:20 UTC, merged